from binance import Client
BINANCE_KEY ="O8yn19mXs8mFGQo3b8wb2sB5fKob8uCvmyEWmnDv1n32xK1CM5dmtdJI6FZwna82"
BINANCE_SECRET = "q7jZLkE1GQes8MKvewpdE2SMv7WxWoSPlQD4nw6x6Vn62nAkNDagSTGDqMSojA5r"
COIN_PAIR = "BTCUSDT"
COIN_PAIRS = ["BTCUSDT","BNBUSDT","ETHUSDT","XRPUSDT","CFXUSDT","LTCUSDT","APTUSDT","SOLUSDT","ADAUSDT","MASKUSDT","DOGEUSDT","STXUSDT","FTMUSDT","OPUSDT","TRXUSDT","LINKUSDT","ETCUSDT","GALAUSDT","DYDXUSDT","GMTUSDT","AVAXUSDT","SANDUSDT","DOTUSDT","LDOUSDT","LINAUSDT"]
TIME_INTERVAL = Client.KLINE_INTERVAL_4HOUR
START_DAY ="1 Mar 2023"